mod cli;
mod config;
mod theme;
mod utils;

use crate::cli::{change_theme, list_themes};
use crate::config::Config;
use crate::theme::{Theme, find_wallpaper};
use crate::utils::cache::clear_cache;
use crate::utils::history::reapply_last_wallpaper;
use anyhow::Result;
use clap::{Parser, Subcommand};

// TODO:  create preview command which displays the palette (and potentially the wallpaper)
// either in ratatui or using ascii characters
//
// TODO: refactor all/most commands to be subcommands
//
// TODO: write tests for all commands
//
// TODO: add --no-cache flag
//
// TODO: support images not in the wallpaper dir
//
// TODO: list command should be a ratatui interactive screen with a searchable list, which
// displays the name, and a color palette preview
//
// TODO: build in some default templates for common tools like waybar and rofi (think like pywal)
//
// TODO: build in a templating system which allows users to create templates which will
// apply theme changes to different tools
//
// TODO: build out custom color-thief implementation
//
// TODO: let user define custom, not autogenerated themes in the config file

#[derive(Parser, Debug)]
#[command(version, about, long_about = None, arg_required_else_help = true)]
struct Args {
    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Create the config file at ~/.config/chlorophyll/config.toml
    Init,
    /// Clear the cache stored in ~/.cache/chlorophyll
    Clear,
    /// List available wallpapers in the wallpapers directory
    List,
    /// Reapply the last used wallpaper theme. Useful for startup sequences
    Reapply,
    /// Apply a theme from a wallpaper in your wallpapers directory
    ///
    /// Usage: chlorophyll from <name>
    From { name: String },
    /// Generate the cache for a wallpaper in your wallpapers directory
    /// without applying it
    ///
    /// Usage: chlorophyll cache <name>
    Cache { name: String },
}

fn main() -> Result<()> {
    let args = Args::parse();
    let config = Config::load()?;

    match args.command {
        Some(Command::Init) => {
            Config::init()?;
        }
        Some(Command::Clear) => {
            clear_cache()?;
        }
        Some(Command::Reapply) => {
            reapply_last_wallpaper()?;
        }
        Some(Command::List) => {
            list_themes(&config.wallpaper_dir)?;
        }
        Some(Command::From { name }) => {
            let path = find_wallpaper(&config.wallpaper_dir, &name)?;
            let theme = Theme::new(path);
            change_theme(&theme)?;
        }
        Some(Command::Cache { name }) => {
            let path = find_wallpaper(&config.wallpaper_dir, &name)?;
            let theme = Theme::new(path);
            // generating the palette will cache the results
            theme.palette()?;
        }
        None => {
            // shouldnt be possible since arg_required_else_help = true, just in case
            anyhow::bail!("No command specified, try chlorophyll --help");
        }
    }

    Ok(())
}
