mod cli;
mod config;
mod templates;
mod theme;
mod utils;

use crate::cli::{change_theme, list_themes};
use crate::config::Config;
use crate::theme::{Theme, find_wallpaper};
use crate::utils::cache::clear_cache;
use crate::utils::history::reapply_last_wallpaper;
use anyhow::Result;
use clap::{Parser, Subcommand};

// TODO:  create preview command which displays the palette (and potentially the wallpaper)
// either in ratatui or using ascii characters
//
// TODO: write tests for all commands
//
// TODO: add --no-cache flag
//
// TODO: list command should be a ratatui interactive screen with a searchable list, which
// displays the name, and a color palette preview
//
// TODO: instead of the copy paste method right now, it would be cool to have a
// template command which write the subcommand name-matched template to their templates folder
// Something like chlorophyll template waybar would write it.
//
// TODO: build out custom color-thief implementation
//
// TODO: let user define custom, not autogenerated themes in the config file
//
#[derive(Parser, Debug)]
#[command(version, about, long_about = None, arg_required_else_help = true)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Create the config file at ~/.config/chlorophyll/config.toml
    Init,
    /// Clear the cache stored in ~/.cache/chlorophyll
    Clear,
    /// List available wallpapers in the wallpapers directory
    List,
    /// Reapply the last used wallpaper theme. Useful for startup sequences
    Reapply,
    /// Apply a theme from a wallpaper in your wallpapers directory
    ///
    /// Usage: chlorophyll from <name>
    From { name: String },
    /// Generate the cache for a wallpaper in your wallpapers directory
    /// without applying it
    ///
    /// Usage: chlorophyll cache <name>
    Cache { name: String },
}

impl Cli {
    fn run(self) -> Result<()> {
        let config = Config::load()?;

        match self.command {
            Command::Init => {
                Config::init()?;
            }
            Command::Clear => {
                clear_cache()?;
            }
            Command::Reapply => {
                reapply_last_wallpaper(&config.templates)?;
            }
            Command::List => {
                list_themes(&config.wallpaper_dir)?;
            }
            Command::From { name } => {
                let path = find_wallpaper(&config.wallpaper_dir, &name)?;
                let theme = Theme::new(path);
                change_theme(&theme, &config.templates)?;
            }
            Command::Cache { name } => {
                let path = find_wallpaper(&config.wallpaper_dir, &name)?;
                let theme = Theme::new(path);
                // generating the palette will cache the results
                theme.palette()?;
            }
        }

        Ok(())
    }
}

fn main() -> Result<()> {
    Cli::parse().run()
}
